'use strict';

import { IMember } from './interfaces';

const members: Array<IMember> = [
  {
    no: 2,
    name: 'Huỳnh Khoan Ái',
    dateOfBirth: '1924-04-07',
    gender: 'Nam',
    province: 'Bắc Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Thị An',
    dateOfBirth: '1917-10-22',
    gender: 'Nữ',
    province: 'Phú Thọ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Anh',
    dateOfBirth: '1912-02-10',
    gender: 'Nam',
    province: 'Thừa Thiên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Tấn Anh (Linh)',
    dateOfBirth: '1916-02-16',
    gender: 'Nam',
    province: 'Hải Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Anh',
    dateOfBirth: '1912-03-01',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Văn Ất',
    dateOfBirth: '1932-12-01',
    gender: 'Nam',
    province: 'Bắc Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Đức Âu (Võ Khải Ca)',
    dateOfBirth: '1914-02-20',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Diệp Ba',
    dateOfBirth: '1916-07-12',
    gender: 'Nam',
    province: 'Mỹ Tho',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Quảng Ba',
    dateOfBirth: '1915-03-18',
    gender: 'Nam',
    province: 'Lạng Sơn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Xuân Bách',
    dateOfBirth: '1924-05-23',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Văn Bạch (Phạm Văn Bạch)',
    dateOfBirth: '1910-06-18',
    gender: 'Nam',
    province: 'Bến Tre',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trịnh Xuân Bái',
    dateOfBirth: '1911-08-15',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Bằng',
    dateOfBirth: '1905-07-01',
    gender: 'Nam',
    province: 'Vĩnh Phúc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Lương Bằng',
    dateOfBirth: '1903-04-01',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Tăng Văn Bằng',
    dateOfBirth: '1923-01-01',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đào Đình Bảng',
    dateOfBirth: '1924-08-14',
    gender: 'Nam',
    province: 'Yên Bái',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Cao Viết Bảo',
    dateOfBirth: '1922-04-01',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Thị Bảo',
    dateOfBirth: '1936-01-01',
    gender: 'Nữ',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hồ Thị Bi',
    dateOfBirth: '1916-04-01',
    gender: 'Nữ',
    province: 'Hoà Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hồ Thành Biên',
    dateOfBirth: '1890-09-10',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Bính',
    dateOfBirth: '1919-05-19',
    gender: 'Nam',
    province: 'Bắc Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Bình',
    dateOfBirth: '1923-09-01',
    gender: 'Nam',
    province: 'Thái Nguyên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Tử Bình',
    dateOfBirth: '1907-05-01',
    gender: 'Nam',
    province: 'Hà Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nịnh Văn Bỉnh (Sửu)',
    dateOfBirth: '1921-04-30',
    gender: 'Nam',
    province: 'Tuyên Quang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trịnh Thị Bỉnh',
    dateOfBirth: '1923-06-01',
    gender: 'Nữ',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Đăng Bộ',
    dateOfBirth: '1925-03-18',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Đình Bông',
    dateOfBirth: '1925-01-15',
    gender: 'Nam',
    province: 'Hồng Quảng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nhữ Văn Bồng',
    dateOfBirth: '1934-10-05',
    gender: 'Nam',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Văn Búng',
    dateOfBirth: '1900-01-01',
    gender: 'Nam',
    province: 'Biên Hòa',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lò Văn Bường',
    dateOfBirth: '1924-02-07',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Tạ Quang Bửu',
    dateOfBirth: '1910-07-23',
    gender: 'Nam',
    province: 'Kiến An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bàn Văn Các',
    dateOfBirth: '1926-12-10',
    gender: 'Nam',
    province: 'Yên Bái',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Cái',
    dateOfBirth: '1907-03-22',
    gender: 'Nam',
    province: 'Bến Tre',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Thị Cầm',
    dateOfBirth: '1920-01-01',
    gender: 'Nữ',
    province: 'Thái Nguyên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bùi Thị Cẩm',
    dateOfBirth: '1912-02-01',
    gender: 'Nữ',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đoàn Văn Cẩm',
    dateOfBirth: '1928-06-03',
    gender: 'Nam',
    province: 'Ninh Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Kha Vạng Cân',
    dateOfBirth: '1908-10-16',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Cân',
    dateOfBirth: '1928-10-01',
    gender: 'Nam',
    province: 'Kiến An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Văn Cẩn',
    dateOfBirth: '1910-08-13',
    gender: 'Nam',
    province: 'Kiến An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Cù Huy Cận',
    dateOfBirth: '1919-05-31',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Cận',
    dateOfBirth: '1900-01-01',
    gender: 'Nam',
    province: 'Vĩnh Phúc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Đình Cào',
    dateOfBirth: '1920-10-01',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Văn Cát',
    dateOfBirth: '1924-11-07',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'La Văn Cầu',
    dateOfBirth: '1931-01-01',
    gender: 'Nam',
    province: 'Cao Bằng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nông Quốc Chấn (Nông Văn Quỳnh)',
    dateOfBirth: '1923-01-18',
    gender: 'Nam',
    province: 'Bắc Kạn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Chấn',
    dateOfBirth: '1920-01-01',
    gender: 'Nam',
    province: 'Bình Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đỗ Hữu Chất',
    dateOfBirth: '1920-06-04',
    gender: 'Nam',
    province: 'Sơn Tây',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đặng Việt Châu',
    dateOfBirth: '1914-07-02',
    gender: 'Nam',
    province: 'Vĩnh Phúc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Kinh Chi',
    dateOfBirth: '1898-12-20',
    gender: 'Nam',
    province: 'Thừa Thiên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Chi',
    dateOfBirth: '1913-09-13',
    gender: 'Nam',
    province: 'Khánh Hoà',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Văn Chiêu',
    dateOfBirth: '1915-06-21',
    gender: 'Nam',
    province: 'Sóc Trăng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trường Chinh',
    dateOfBirth: '1907-02-09',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Quang Chính',
    dateOfBirth: '1918-01-01',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Chương (Nguyễn Đức Lương)',
    dateOfBirth: '1918-10-01',
    gender: 'Nam',
    province: 'Kiến An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phùng Lê Chưởng',
    dateOfBirth: '1917-01-01',
    gender: 'Nam',
    province: 'Lạng Sơn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Huy Cơ',
    dateOfBirth: '1900-04-15',
    gender: 'Nam',
    province: 'Bắc Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Côn',
    dateOfBirth: '1893-12-27',
    gender: 'Nam',
    province: 'Gò Công',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Côn',
    dateOfBirth: '1917-05-15',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Cổn',
    dateOfBirth: '1911-05-18',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Công',
    dateOfBirth: '1925-11-20',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Công',
    dateOfBirth: '1893-12-27',
    gender: 'Nam',
    province: 'Gò Công',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Văn Cống',
    dateOfBirth: '1926-12-23',
    gender: 'Nam',
    province: 'Kiến An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lương Định Của',
    dateOfBirth: '1920-07-01',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Thị Cúc (Len)',
    dateOfBirth: '1916-10-01',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Văn Cung',
    dateOfBirth: '1906-05-05',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn An Cương',
    dateOfBirth: '1932-12-28',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Cửu',
    dateOfBirth: '1902-09-08',
    gender: 'Nam',
    province: 'Sa Đéc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Tất Đắc',
    dateOfBirth: '1906-10-10',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Văn Đại',
    dateOfBirth: '1915-01-01',
    gender: 'Nam',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trương Đình Dần',
    dateOfBirth: '1910-01-01',
    gender: 'Nam',
    province: 'Ninh Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Đăng',
    dateOfBirth: '1921-11-01',
    gender: 'Nam',
    province: 'Cần Thơ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Phương Danh (Tám Danh)',
    dateOfBirth: '1901-01-01',
    gender: 'Nam',
    province: 'Quảng Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Kim Đao (Giàng Văn Pao)',
    dateOfBirth: '1910-11-11',
    gender: 'Nam',
    province: 'Cao Bằng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Văn Đáo',
    dateOfBirth: '1911-08-01',
    gender: 'Nam',
    province: 'Vĩnh Linh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thị Đạo',
    dateOfBirth: '1915-08-15',
    gender: 'Nam',
    province: 'Bắc Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thế Đạt',
    dateOfBirth: '1926-09-02',
    gender: 'Nam',
    province: 'Thái Nguyên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hỷ Vầy Dẩu (A DÓNG)',
    dateOfBirth: '1929-03-03',
    gender: 'Nam',
    province: 'Hải Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Tô Quang Đẩu',
    dateOfBirth: '1907-11-19',
    gender: 'Nam',
    province: 'Kiến An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Văn Đệ',
    dateOfBirth: '1936-04-11',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hồ Đắc Di',
    dateOfBirth: '1900-04-08',
    gender: 'Nam',
    province: 'Tuyên Quang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bùi Thị Diệm (Lê Phương)',
    dateOfBirth: '1920-10-20',
    gender: 'Nữ',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Văn Diệm',
    dateOfBirth: '1913-02-25',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Thị Hồng Điệp',
    dateOfBirth: '1929-01-01',
    gender: 'Nữ',
    province: 'Hà Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trịnh Ngọc Điệt',
    dateOfBirth: '1917-01-01',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Diêu (Phan Diêu)',
    dateOfBirth: '1912-09-11',
    gender: 'Nam',
    province: 'Quảng Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Công Dỉnh',
    dateOfBirth: '1925-04-04',
    gender: 'Nam',
    province: 'Lạng Sơn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Trung Đình (Nguyễn Cung)',
    dateOfBirth: '1914-01-01',
    gender: 'Nam',
    province: 'Khu tự trị Thái Mèo',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lã Xuân Đỉnh',
    dateOfBirth: '1921-11-01',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Thị Định',
    dateOfBirth: '1925-01-01',
    gender: 'Nữ',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hòa thượng Thích Trí Độ (Thích Trí Độ)',
    dateOfBirth: '1895-12-15',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Độ (Tạ Ngọc Phách)',
    dateOfBirth: '1923-01-01',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ngô Duy Đông',
    dateOfBirth: '1917-01-16',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Văn Đồng',
    dateOfBirth: '1906-03-01',
    gender: 'Nam',
    province: 'Quảng Ngãi',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Y Wuang Mlô Duôn Du',
    dateOfBirth: '1911-03-12',
    gender: 'Nam',
    province: 'Đắc Lắk',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Quang Dụ',
    dateOfBirth: '1909-04-27',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Duân',
    dateOfBirth: '1910-06-11',
    gender: 'Nam',
    province: 'Quảng Ngãi',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Duẩn',
    dateOfBirth: '1907-01-01',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Hữu Dực',
    dateOfBirth: '1910-01-05',
    gender: 'Nam',
    province: 'Thừa Thiên - Huế',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Minh Đức',
    dateOfBirth: '1922-03-17',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Dung',
    dateOfBirth: '1907-05-04',
    gender: 'Nam',
    province: 'TP Đà Nẵng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hòa thượng Trần Quảng Dung (Trần Quảng Dung)',
    dateOfBirth: '1904-08-19',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Văn Tiến Dũng',
    dateOfBirth: '1917-05-02',
    gender: 'Nam',
    province: 'Bắc Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Duy Dương',
    dateOfBirth: '1921-09-28',
    gender: 'Nam',
    province: 'Hưng Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Dương (Vũ Dương)',
    dateOfBirth: '1910-01-28',
    gender: 'Nam',
    province: 'Vĩnh Phúc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Hữu Duyệt',
    dateOfBirth: '1906-10-02',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Huỳnh Văn Gấm',
    dateOfBirth: '1922-03-10',
    gender: 'Nam',
    province: 'Tân An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bùi Hưng Gia',
    dateOfBirth: '1906-01-01',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Ngọc Giác (Trần Thắng)',
    dateOfBirth: '1924-12-01',
    gender: 'Nam',
    province: 'Kiến An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Minh Giám',
    dateOfBirth: '1905-11-02',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đặng Kim Giang',
    dateOfBirth: '1909-07-14',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trương Quang Giao',
    dateOfBirth: '1910-03-10',
    gender: 'Nam',
    province: 'Bắc Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Võ Nguyên Giáp',
    dateOfBirth: '1911-01-01',
    gender: 'Nam',
    province: 'Quảng Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Sơn Hà',
    dateOfBirth: '1894-01-01',
    gender: 'Nam',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Văn Hạ',
    dateOfBirth: '1922-03-25',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ngô Tử Hạ',
    dateOfBirth: '1882-01-01',
    gender: 'Nam',
    province: 'Ninh Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lò Văn Hạc',
    dateOfBirth: '1914-02-10',
    gender: 'Nam',
    province: 'Khu tự trị Thái Mèo',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lò Văn Hặc',
    dateOfBirth: '1914-01-01',
    gender: 'Nam',
    province: 'Lai Châu',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Xuân Hàm',
    dateOfBirth: '1911-04-03',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Hanh',
    dateOfBirth: '1900-01-01',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đào Thị Hạnh',
    dateOfBirth: '1933-10-01',
    gender: 'Nữ',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thúc Hào',
    dateOfBirth: '1912-10-11',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Văn Hiến',
    dateOfBirth: '1904-09-15',
    gender: 'Nam',
    province: 'Quảng Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Cao Thị Hiền',
    dateOfBirth: '1925-01-01',
    gender: 'Nam',
    province: 'Vĩnh Phúc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Dương Đức Hiền',
    dateOfBirth: '1917-01-01',
    gender: 'Nam',
    province: 'Bắc Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Minh Hiền',
    dateOfBirth: '1919-06-01',
    gender: 'Nữ',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Thị Hiền (Vũ Thị Lãm)',
    dateOfBirth: '1936-07-28',
    gender: 'Nữ',
    province: 'Kiến An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Dương Kỳ Hiệp',
    dateOfBirth: '1911-04-14',
    gender: 'Nam',
    province: 'Sóc Trăng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đỗ Khắc Hiếu',
    dateOfBirth: '1923-12-01',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hồ Trọng Hiếu (Tú Mỡ)',
    dateOfBirth: '1900-01-01',
    gender: 'Nam',
    province: 'Bắc Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Công Hòa (Nguyễn Hữu Túc)',
    dateOfBirth: '1907-05-01',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Thào Doãn Hòa',
    dateOfBirth: '1932-04-01',
    gender: 'Nam',
    province: 'Lào Cai',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Văn Hoan',
    dateOfBirth: '1905-01-01',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Quốc Hoàn',
    dateOfBirth: '1916-01-23',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Hoàng',
    dateOfBirth: '1910-11-11',
    gender: 'Nam',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Phi Hoanh',
    dateOfBirth: '1905-10-18',
    gender: 'Nam',
    province: 'Mỹ Tho',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Hoành',
    dateOfBirth: '1907-01-01',
    gender: 'Nam',
    province: 'Chợ Lớn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Dương Công Hoạt',
    dateOfBirth: '1912-05-15',
    gender: 'Nam',
    province: 'Cao Bằng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Bá Hòe',
    dateOfBirth: '1896-01-01',
    gender: 'Nam',
    province: 'PleiKu',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lương Duyên Hồi',
    dateOfBirth: '1902-08-12',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Khoa Diệu Hồng',
    dateOfBirth: '1914-09-01',
    gender: 'Nữ',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thị Hồng',
    dateOfBirth: '1930-02-01',
    gender: 'Nữ',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Văn Hồng',
    dateOfBirth: '1908-01-01',
    gender: 'Nam',
    province: 'Ninh Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đỗ Xuân Hợp',
    dateOfBirth: '1906-07-08',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng A Hù',
    dateOfBirth: '1920-10-01',
    gender: 'Nam',
    province: 'Khu tự trị Thái Mèo',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ngô Thị Huệ',
    dateOfBirth: '1919-07-01',
    gender: 'Nữ',
    province: 'Bạc Liêu',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Huệ',
    dateOfBirth: '1913-06-29',
    gender: 'Nam',
    province: 'Sa Đéc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Thị Huệ',
    dateOfBirth: '1927-01-01',
    gender: 'Nữ',
    province: 'Hưng Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Hùng (Phạm Văn Thiện)',
    dateOfBirth: '1912-06-11',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Mạnh Hưng (Nguyễn Văn Xê)',
    dateOfBirth: '1916-09-23',
    gender: 'Nam',
    province: 'Bắc Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Hưng (Phan Văn Ứng)',
    dateOfBirth: '1914-07-15',
    gender: 'Nam',
    province: 'Hà Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Duy Hưng',
    dateOfBirth: '1912-01-16',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Hưởng (Thành Tâm)',
    dateOfBirth: '1906-12-24',
    gender: 'Nam',
    province: 'Long Xuyên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Tố Hữu',
    dateOfBirth: '1920-10-04',
    gender: 'Nam',
    province: 'Ninh Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Huy',
    dateOfBirth: '1908-10-01',
    gender: 'Nam',
    province: 'Bình Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Huyên',
    dateOfBirth: '1912-11-16',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Quách Hy',
    dateOfBirth: '1907-02-01',
    gender: 'Nam',
    province: 'Hoà Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trương Quang Hy',
    dateOfBirth: '1906-02-03',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vi Xuân Hỷ (Việt Tân)',
    dateOfBirth: '1917-06-11',
    gender: 'Nam',
    province: 'Hải Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Đình Kế',
    dateOfBirth: '1922-08-20',
    gender: 'Nam',
    province: 'Phú Thọ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vù Mí Kẻ (Vù Mí Dình)',
    dateOfBirth: '1930-12-25',
    gender: 'Nam',
    province: 'Hà Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Duy Khâm',
    dateOfBirth: '1911-07-15',
    gender: 'Nam',
    province: 'Trà Vinh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ngô Gia Khảm',
    dateOfBirth: '1912-12-25',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Khang',
    dateOfBirth: '1919-01-01',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Quang Khanh',
    dateOfBirth: '1912-01-01',
    gender: 'Nam',
    province: 'Bình Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Ngọc Khánh',
    dateOfBirth: '1928-12-01',
    gender: 'Nam',
    province: 'Vĩnh Phúc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ung Văn Khiêm',
    dateOfBirth: '1910-03-03',
    gender: 'Nam',
    province: 'Long Xuyên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Tạ Duy Khiết (Hồng Thanh)',
    dateOfBirth: '1928-01-01',
    gender: 'Nam',
    province: 'Hà Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Hữu Khiếu',
    dateOfBirth: '1915-10-15',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thị Khoa',
    dateOfBirth: '1931-02-01',
    gender: 'Nữ',
    province: 'Hoà Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Đăng Khoa',
    dateOfBirth: '1907-04-05',
    gender: 'Nam',
    province: 'Thừa Thiên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đỗ Đức Khóa',
    dateOfBirth: '1916-01-17',
    gender: 'Nam',
    province: 'Phú Thọ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Trường Khoát',
    dateOfBirth: '1913-02-07',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Xuân Khoát',
    dateOfBirth: '1910-02-12',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Văn Khung',
    dateOfBirth: '1923-12-21',
    gender: 'Nam',
    province: 'Gia Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Thị Kiệm',
    dateOfBirth: '1924-02-01',
    gender: 'Nữ',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bùi Văn Kín',
    dateOfBirth: '1920-11-05',
    gender: 'Nam',
    province: 'Hoà Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Kỉnh',
    dateOfBirth: '1916-02-28',
    gender: 'Nam',
    province: 'Hà Tiên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ngụy Như KonTum',
    dateOfBirth: '1913-05-03',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đoàn Hồng Kỳ',
    dateOfBirth: '1913-01-13',
    gender: 'Nam',
    province: 'Cao Bằng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Xuân Kỷ',
    dateOfBirth: '1886-12-19',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Văn Lai',
    dateOfBirth: '1894-07-01',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Lam',
    dateOfBirth: '1922-12-31',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bùi Lâm',
    dateOfBirth: '1905-12-15',
    gender: 'Nam',
    province: 'Hà Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Ngọc Lạt',
    dateOfBirth: '1924-10-10',
    gender: 'Nam',
    province: 'Lào Cai',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thành Lê (Lê Thanh Thủy)',
    dateOfBirth: '1920-06-17',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Lê',
    dateOfBirth: '1921-01-01',
    gender: 'Nam',
    province: 'Bình Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trương Thị Len',
    dateOfBirth: '1938-09-10',
    gender: 'Nữ',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đinh Văn Liên',
    dateOfBirth: '1907-02-12',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thị Liêu (Hồ)',
    dateOfBirth: '1915-03-01',
    gender: 'Nữ',
    province: 'Bắc Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lò Văn Liệu',
    dateOfBirth: '1903-07-01',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Huy Liệu',
    dateOfBirth: '1901-10-13',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Lợ',
    dateOfBirth: '1926-06-15',
    gender: 'Nam',
    province: 'Quảng Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Lộc',
    dateOfBirth: '1914-01-01',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Hồng Long',
    dateOfBirth: '1912-10-11',
    gender: 'Nam',
    province: 'Quảng Ngãi',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Lư',
    dateOfBirth: '1925-02-16',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thế Lữ',
    dateOfBirth: '1907-06-10',
    gender: 'Nam',
    province: 'Bắc Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Văn Luân',
    dateOfBirth: '1910-10-19',
    gender: 'Nam',
    province: 'Rạch Giá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bồ Xuân Luật',
    dateOfBirth: '1913-02-20',
    gender: 'Nam',
    province: 'Hưng Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Lục',
    dateOfBirth: '1920-06-10',
    gender: 'Nam',
    province: 'Hồng Quảng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Quang Lược',
    dateOfBirth: '1891-10-01',
    gender: 'Nam',
    province: 'Quảng Ngãi',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Văn Luôn',
    dateOfBirth: '1930-10-19',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Triệu Tạ Luồng',
    dateOfBirth: '1926-01-01',
    gender: 'Nam',
    province: 'Hà Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Kim Xuyến Lượng',
    dateOfBirth: '1927-03-06',
    gender: 'Nam',
    province: 'Hà Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Viết Lượng',
    dateOfBirth: '1906-05-26',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Huỳnh Lưu',
    dateOfBirth: '1905-03-15',
    gender: 'Nam',
    province: 'Phú Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lương Văn Lưu',
    dateOfBirth: '1905-01-08',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Cao Luyện',
    dateOfBirth: '1908-03-01',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Lý',
    dateOfBirth: '1912-02-05',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Dương Bạch Mai',
    dateOfBirth: '1904-01-01',
    gender: 'Nam',
    province: 'Bà Rịa',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đặng Thai Mai',
    dateOfBirth: '1902-12-24',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Văn Mai',
    dateOfBirth: '1916-10-20',
    gender: 'Nam',
    province: 'Bình Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Hữu Mai',
    dateOfBirth: '1915-10-10',
    gender: 'Nam',
    province: 'Hưng Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bùi Quang Mại',
    dateOfBirth: '1921-01-01',
    gender: 'Nam',
    province: 'Vĩnh Phúc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Chu Huy Mân',
    dateOfBirth: '1913-01-01',
    gender: 'Nam',
    province: 'Khu tự trị Thái Mèo',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Kim Mạnh',
    dateOfBirth: '1919-01-01',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Mậu (Nguyễn Văn Khai)',
    dateOfBirth: '1907-02-02',
    gender: 'Nam',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trịnh Thị Miếng',
    dateOfBirth: '1915-11-07',
    gender: 'Nữ',
    province: 'Gia Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Trường Minh (Hoàng Khải Luận)',
    dateOfBirth: '1922-12-01',
    gender: 'Nam',
    province: 'Lào Cai',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hồ Chí Minh',
    dateOfBirth: '1890-05-19',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Tấn Minh',
    dateOfBirth: '1923-08-02',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Minh',
    dateOfBirth: '1923-01-08',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Gia Mô',
    dateOfBirth: '1925-01-01',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đặng Thị Mùi',
    dateOfBirth: '1929-12-05',
    gender: 'Nữ',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đỗ Mười',
    dateOfBirth: '1917-02-02',
    gender: 'Nam',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Tiến Mỹ',
    dateOfBirth: '1932-11-11',
    gender: 'Nam',
    province: 'Hưng Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Năm',
    dateOfBirth: '1923-09-14',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thị Năm',
    dateOfBirth: '1914-04-03',
    gender: 'Nữ',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Thị Năm',
    dateOfBirth: '1914-08-20',
    gender: 'Nữ',
    province: 'Bắc Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Đình Ngân',
    dateOfBirth: '1891-06-24',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hồ Thiệu Ngạn (Hồ Công Nghĩa)',
    dateOfBirth: '1907-01-15',
    gender: 'Nam',
    province: 'Châu Đốc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Nghi',
    dateOfBirth: '1917-01-18',
    gender: 'Nam',
    province: 'Phú Thọ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Thanh Nghị',
    dateOfBirth: '1911-03-06',
    gender: 'Nam',
    province: 'Hồng Quảng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Văn Nghĩa',
    dateOfBirth: '1933-03-06',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Tử Nghĩa',
    dateOfBirth: '1910-10-23',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Đại Nghĩa',
    dateOfBirth: '1913-01-01',
    gender: 'Nam',
    province: 'Phú Thọ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Hữu Nghĩa',
    dateOfBirth: '1914-12-20',
    gender: 'Nam',
    province: 'Phú Thọ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Tôn Viết Nghiệm',
    dateOfBirth: '1918-05-15',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hà Văn Nghiệp',
    dateOfBirth: '1917-01-27',
    gender: 'Nam',
    province: 'Hoà Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Văn Ngoạn',
    dateOfBirth: '1917-01-01',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Kim Ngọc',
    dateOfBirth: '1917-10-10',
    gender: 'Nam',
    province: 'Vĩnh Phú',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Đình Ngữ',
    dateOfBirth: '1922-02-26',
    gender: 'Nam',
    province: 'Hoà Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Ngưa',
    dateOfBirth: '1912-02-01',
    gender: 'Nam',
    province: 'Hưng Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Xuân Nguyên',
    dateOfBirth: '1904-02-21',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Văn Nguyên',
    dateOfBirth: '1904-10-16',
    gender: 'Nam',
    province: 'Gia Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thị Minh Nhã',
    dateOfBirth: '1921-10-20',
    gender: 'Nữ',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Văn Nhàn',
    dateOfBirth: '1921-01-29',
    gender: 'Nam',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Hữu Nhân',
    dateOfBirth: '1920-02-20',
    gender: 'Nam',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đỗ Đức Nhận',
    dateOfBirth: '1912-04-01',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bùi Văn Nhẹ',
    dateOfBirth: '1930-07-04',
    gender: 'Nam',
    province: 'Kiến An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Nhiên',
    dateOfBirth: '1922-01-03',
    gender: 'Nam',
    province: 'Cao Bằng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ngô Tấn Nhơn',
    dateOfBirth: '1914-09-15',
    gender: 'Nam',
    province: 'Mỹ Tho',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Xuân Như',
    dateOfBirth: '1917-05-01',
    gender: 'Nam',
    province: 'Bình Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phùng Hữu Nhung',
    dateOfBirth: '1910-02-01',
    gender: 'Nam',
    province: 'Thái Nguyên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Y Ngông NiêkĐăm',
    dateOfBirth: '1922-08-13',
    gender: 'Nam',
    province: 'Đắc Lắk',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Văn Nĩnh',
    dateOfBirth: '1918-05-10',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Oắng',
    dateOfBirth: '1914-10-14',
    gender: 'Nam',
    province: 'Gia Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đinh Văn Oanh',
    dateOfBirth: '1934-10-01',
    gender: 'Nam',
    province: 'Hưng Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Giàng A Páo',
    dateOfBirth: '1923-10-09',
    gender: 'Nam',
    province: 'Lai Châu',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Giàng A Páo',
    dateOfBirth: '1924-01-01',
    gender: 'Nam',
    province: 'Yên Bái',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hồ Vàng Páo',
    dateOfBirth: '1924-01-01',
    gender: 'Nam',
    province: 'Lào Cai',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'An Văn Pháp',
    dateOfBirth: '1911-12-05',
    gender: 'Nam',
    province: 'Hà Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Huỳnh Tấn Phát',
    dateOfBirth: '1913-01-01',
    gender: 'Nam',
    province: 'Mỹ Tho',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Phát',
    dateOfBirth: '1909-01-19',
    gender: 'Nam',
    province: 'Vĩnh Long',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trương Tấn Phát (Trần Phong Quế)',
    dateOfBirth: '1915-06-15',
    gender: 'Nam',
    province: 'Châu Đốc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Tôn Quang Phiệt',
    dateOfBirth: '1900-11-04',
    gender: 'Nam',
    province: 'Thành phố Huế',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nay Phin',
    dateOfBirth: '1919-02-24',
    gender: 'Nam',
    province: 'PleiKu',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Sĩ Phong',
    dateOfBirth: '1920-05-01',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Võ Phong (Nguyễn Đức Thái)',
    dateOfBirth: '1910-03-04',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Dương Văn Phúc',
    dateOfBirth: '1910-01-01',
    gender: 'Nam',
    province: 'Trà Vinh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Phúc',
    dateOfBirth: '1910-01-01',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hồ Văn Phúng (Ích Hậu)',
    dateOfBirth: '1921-12-11',
    gender: 'Nam',
    province: 'Bắc Kạn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đỗ Phụng (Trần Quang Trọng)',
    dateOfBirth: '1927-10-15',
    gender: 'Nam',
    province: 'Bắc Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Chân Phương',
    dateOfBirth: '1925-01-25',
    gender: 'Nữ',
    province: 'Sơn Tây',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ngô Duy Phương',
    dateOfBirth: '1923-10-24',
    gender: 'Nam',
    province: 'Bắc Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Triệu Khánh Phương (Triệu Nho Phúc)',
    dateOfBirth: '1913-04-21',
    gender: 'Nam',
    province: 'Thái Nguyên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Thái Phượng',
    dateOfBirth: '1918-06-29',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ngô Thị Pứng (Bẩy)',
    dateOfBirth: '1915-10-11',
    gender: 'Nữ',
    province: 'Cao Bằng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đặng Văn Quang (Đặng Quang Minh)',
    dateOfBirth: '1909-11-02',
    gender: 'Nam',
    province: 'Cần Thơ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đỗ Phát Quang',
    dateOfBirth: '1911-07-18',
    gender: 'Nam',
    province: 'Bến Tre',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Thị Quang',
    dateOfBirth: '1910-01-08',
    gender: 'Nữ',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Quang',
    dateOfBirth: '1926-03-18',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Quê',
    dateOfBirth: '1901-02-12',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Ngọc Quế',
    dateOfBirth: '1902-01-01',
    gender: 'Nam',
    province: 'Cần Thơ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Quế',
    dateOfBirth: '1924-04-01',
    gender: 'Nam',
    province: 'Vĩnh Phúc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hà Thị Quế',
    dateOfBirth: '1921-08-15',
    gender: 'Nữ',
    province: 'Bắc Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Ngọc Quế',
    dateOfBirth: '1908-01-01',
    gender: 'Nam',
    province: 'Phú Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Thị Quế',
    dateOfBirth: '1919-02-01',
    gender: 'Nữ',
    province: 'Ninh Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Tôn Thị Quế',
    dateOfBirth: '1902-08-10',
    gender: 'Nữ',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Quế',
    dateOfBirth: '1901-01-01',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Quan Văn Quý (Ngọc Thuyết)',
    dateOfBirth: '1929-01-05',
    gender: 'Nam',
    province: 'Tuyên Quang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lang Viết Quý',
    dateOfBirth: '1928-10-12',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lý Tiến Quý',
    dateOfBirth: '1929-06-01',
    gender: 'Nam',
    province: 'Khu tự trị Thái Mèo',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Quý',
    dateOfBirth: '1922-04-01',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Mạnh Quỳ',
    dateOfBirth: '1912-01-01',
    gender: 'Nam',
    province: 'Quảng Trị',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Như Quỹ',
    dateOfBirth: '1906-03-12',
    gender: 'Nam',
    province: 'Thái Nguyên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Quỳnh',
    dateOfBirth: '1920-01-01',
    gender: 'Nam',
    province: 'Phú Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Sâm',
    dateOfBirth: '1915-07-01',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lò Văn San',
    dateOfBirth: '1911-03-17',
    gender: 'Nam',
    province: 'Khu tự trị Thái Mèo',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn San',
    dateOfBirth: '1922-06-12',
    gender: 'Nam',
    province: 'Lạng Sơn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Đức Sản',
    dateOfBirth: '1911-01-01',
    gender: 'Nam',
    province: 'Vĩnh Linh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Sanh',
    dateOfBirth: '1911-02-12',
    gender: 'Nam',
    province: 'Bình Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trương Thị Sáu (Nguyễn An Ninh)',
    dateOfBirth: '1899-06-26',
    gender: 'Nữ',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Thị Sen',
    dateOfBirth: '1933-01-01',
    gender: 'Nam',
    province: 'Phú Thọ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Võ Thị Siêng',
    dateOfBirth: '1900-01-01',
    gender: 'Nữ',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Nguyên Sinh (Nguyễn Ngọc Mạo (tức Mại))',
    dateOfBirth: '1925-10-15',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thanh Sơn (Nguyễn Văn Tây)',
    dateOfBirth: '1910-11-05',
    gender: 'Nam',
    province: 'Trà Vinh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đặng Đức Song',
    dateOfBirth: '1934-08-01',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Sót',
    dateOfBirth: '1929-08-20',
    gender: 'Nam',
    province: 'Hồng Quảng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Sử',
    dateOfBirth: '1905-04-04',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Văn Sử',
    dateOfBirth: '1910-01-15',
    gender: 'Nam',
    province: 'Vĩnh Long',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lâm Sung',
    dateOfBirth: '1918-03-27',
    gender: 'Nam',
    province: 'Lai Châu',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trương Sỹ',
    dateOfBirth: '1915-10-01',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Công Tâm (Nguyễn Xuân Nhĩ)',
    dateOfBirth: '1912-01-01',
    gender: 'Nam',
    province: 'Quảng Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lò Văn Tân',
    dateOfBirth: '1925-06-03',
    gender: 'Nam',
    province: 'Khu tự trị Thái Mèo',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Chu Văn Tấn',
    dateOfBirth: '1910-05-01',
    gender: 'Nam',
    province: 'Thái Nguyên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đào Thị Tấn',
    dateOfBirth: '1932-01-01',
    gender: 'Nữ',
    province: 'Hưng Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hà Kế Tấn',
    dateOfBirth: '1914-01-01',
    gender: 'Nam',
    province: 'Vĩnh Phúc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Tấn',
    dateOfBirth: '1922-10-20',
    gender: 'Nam',
    province: 'Vĩnh Phúc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nghiêm Khắc Tặng',
    dateOfBirth: '1911-09-01',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bùi Quang Tạo',
    dateOfBirth: '1913-01-01',
    gender: 'Nam',
    province: 'Phú Thọ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Tạo (Nguyễn Phú Doãn)',
    dateOfBirth: '1905-11-11',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Tạo',
    dateOfBirth: '1923-02-12',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Tạo',
    dateOfBirth: '1908-05-20',
    gender: 'Nam',
    province: 'Rạch Giá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Tạo',
    dateOfBirth: '1916-07-13',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Tế',
    dateOfBirth: '1930-11-01',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Dương Mạc Thạch (Xích Thắng)',
    dateOfBirth: '1915-08-05',
    gender: 'Nam',
    province: 'Hà Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Ngọc Thạch',
    dateOfBirth: '1909-05-02',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Cao Thắng',
    dateOfBirth: '1923-08-20',
    gender: 'Nam',
    province: 'Hưng Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đinh Văn Thắng',
    dateOfBirth: '1914-01-01',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Tôn Đức Thắng',
    dateOfBirth: '1888-08-20',
    gender: 'Nam',
    province: 'Sài Gòn-Chợ Lớn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bàn Chí Thanh (Hàm)',
    dateOfBirth: '1927-01-07',
    gender: 'Nam',
    province: 'Tuyên Quang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoài Thanh (Nguyễn Đức Nguyên)',
    dateOfBirth: '1909-07-15',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Chí Thanh',
    dateOfBirth: '1914-01-01',
    gender: 'Nam',
    province: 'Vĩnh Linh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Lưu Thanh',
    dateOfBirth: '1907-01-01',
    gender: 'Nam',
    province: 'Phú Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Mậu Thành',
    dateOfBirth: '1909-01-01',
    gender: 'Nam',
    province: 'Hải Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Thành (Nguyễn Trọng Đạt)',
    dateOfBirth: '1922-02-01',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Thành (Thanh Phong)',
    dateOfBirth: '1929-10-10',
    gender: 'Nam',
    province: 'Vĩnh Phúc',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Viết Thành (Vũ Anh)',
    dateOfBirth: '1904-03-14',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vương Chí Thành (Vương Chí Sình)',
    dateOfBirth: '1888-01-01',
    gender: 'Nam',
    province: 'Hà Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Thao',
    dateOfBirth: '1915-01-25',
    gender: 'Nam',
    province: 'Quảng Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Thị Thạo',
    dateOfBirth: '1932-02-01',
    gender: 'Nữ',
    province: 'Ninh Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thị Thập (Nguyễn Thị Ngọc Tốt)',
    dateOfBirth: '1908-10-10',
    gender: 'Nữ',
    province: 'Mỹ Tho',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ma Văn Thay',
    dateOfBirth: '1919-01-20',
    gender: 'Nam',
    province: 'Quảng Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đào Thiện Thi',
    dateOfBirth: '1920-02-23',
    gender: 'Nam',
    province: 'Khánh Hoà',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Đình Thi',
    dateOfBirth: '1924-12-20',
    gender: 'Nam',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Thi',
    dateOfBirth: '1981-09-21',
    gender: 'Nam',
    province: 'Ninh Thuận',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đặng Thí',
    dateOfBirth: '1921-01-01',
    gender: 'Nam',
    province: 'Quảng Trị',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Văn Thiêm',
    dateOfBirth: '1919-03-29',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Sĩ Thiêm',
    dateOfBirth: '1901-08-20',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hà Thị Thiệm',
    dateOfBirth: '1932-05-01',
    gender: 'Nữ',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Chu Thiện',
    dateOfBirth: '1900-01-01',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Đình Thiệp',
    dateOfBirth: '1913-07-02',
    gender: 'Nam',
    province: 'Phúc Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Công Thiệp',
    dateOfBirth: '1904-02-01',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hồ Thiết',
    dateOfBirth: '1900-03-01',
    gender: 'Nam',
    province: 'Quảng Ngãi',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Thiệt',
    dateOfBirth: '1909-01-06',
    gender: 'Nam',
    province: 'Vĩnh Long',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đặng Xuân Thiều',
    dateOfBirth: '1909-01-01',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Quốc Thịnh (Hoàng Hà Châu)',
    dateOfBirth: '1913-01-01',
    gender: 'Nam',
    province: 'Bắc Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thị Thiu',
    dateOfBirth: '1907-01-01',
    gender: 'Nữ',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Tiến Thọ',
    dateOfBirth: '1910-06-09',
    gender: 'Nam',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trịnh Huy Thoan (Đoan)',
    dateOfBirth: '1914-01-01',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Tư Thoan',
    dateOfBirth: '1920-10-20',
    gender: 'Nam',
    province: 'Quảng Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Thơi',
    dateOfBirth: '1912-10-01',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Au Thị Lê Thơm',
    dateOfBirth: '1928-08-12',
    gender: 'Nữ',
    province: 'Lạng Sơn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Quang Thông',
    dateOfBirth: '1880-10-01',
    gender: 'Nam',
    province: 'Quảng Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Huy Thông',
    dateOfBirth: '1916-11-22',
    gender: 'Nam',
    province: 'Hưng Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Mong Thoong',
    dateOfBirth: '1920-02-15',
    gender: 'Nam',
    province: 'Bình Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Tạ Xuân Thu (Tạ Quốc Tiêu)',
    dateOfBirth: '1916-01-01',
    gender: 'Nam',
    province: 'TP Hải Phòng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thị Thú',
    dateOfBirth: '1938-01-01',
    gender: 'Nữ',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lâm Trọng Thư',
    dateOfBirth: '1923-10-23',
    gender: 'Nam',
    province: 'Lạng Sơn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Hữu Thụ',
    dateOfBirth: '1926-01-01',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lâm Quang Thự',
    dateOfBirth: '1905-09-14',
    gender: 'Nam',
    province: 'Quảng Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Đức Thừa',
    dateOfBirth: '1921-06-16',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lưu Huy Thuận',
    dateOfBirth: '1921-01-07',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trịnh Thuận',
    dateOfBirth: '1921-11-01',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Khương Xuân Thực',
    dateOfBirth: '1915-01-01',
    gender: 'Nam',
    province: 'Sơn Tây',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Thuế (Nguyễn Văn Mười)',
    dateOfBirth: '1930-10-01',
    gender: 'Nam',
    province: 'Hà Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Huy Thung',
    dateOfBirth: '1921-01-09',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Đạo Thúy',
    dateOfBirth: '1900-01-01',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Xuân Thủy (Nguyễn Trọng Nhâm)',
    dateOfBirth: '1912-09-02',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ngô Thuyền',
    dateOfBirth: '1910-10-01',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hồ Quang Tiêm',
    dateOfBirth: '1928-05-24',
    gender: 'Nam',
    province: 'Bắc Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lại Duy Tiến',
    dateOfBirth: '1917-01-21',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Mạnh Tiển',
    dateOfBirth: '1906-08-15',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Huỳnh Văn Tiểng',
    dateOfBirth: '1920-10-10',
    gender: 'Nam',
    province: 'Sài Gòn-Chợ Lớn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đỗ Văn Tiết',
    dateOfBirth: '1909-03-08',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Tín',
    dateOfBirth: '1917-07-23',
    gender: 'Nam',
    province: 'Bình Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hà Văn Tính',
    dateOfBirth: '1911-01-01',
    gender: 'Nam',
    province: 'Quảng Ngãi',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Tính',
    dateOfBirth: '1909-04-13',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Hữu Tình',
    dateOfBirth: '1913-03-03',
    gender: 'Nam',
    province: 'Hưng Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Triệu Văn Tịnh',
    dateOfBirth: '1924-06-16',
    gender: 'Nam',
    province: 'Bắc Kạn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phó Đức Tố',
    dateOfBirth: '1903-12-30',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hồ Tơ',
    dateOfBirth: '1897-05-01',
    gender: 'Nam',
    province: 'Vĩnh Linh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bùi Văn Tọa',
    dateOfBirth: '1929-03-15',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lương Văn Toàn',
    dateOfBirth: '1920-09-06',
    gender: 'Nam',
    province: 'Yên Bái',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Khánh Toàn',
    dateOfBirth: '1905-08-01',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Tống',
    dateOfBirth: '1916-04-04',
    gender: 'Nam',
    province: 'Quảng Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Công Tốt',
    dateOfBirth: '1917-08-08',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Trác',
    dateOfBirth: '1904-11-04',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Trân',
    dateOfBirth: '1917-01-01',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Trấn',
    dateOfBirth: '1914-03-21',
    gender: 'Nam',
    province: 'Sài Gòn-Chợ Lớn',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Đình Tri',
    dateOfBirth: '1915-04-10',
    gender: 'Nam',
    province: 'Quảng Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Trí',
    dateOfBirth: '1909-05-15',
    gender: 'Nam',
    province: 'Quảng Ngãi',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Huỳnh Triếp',
    dateOfBirth: '1904-01-01',
    gender: 'Nam',
    province: 'Bình Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đinh Gia Trinh',
    dateOfBirth: '1915-02-15',
    gender: 'Nam',
    province: 'Hà Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Duy Trinh',
    dateOfBirth: '1910-07-15',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Thị Trinh (Lân)',
    dateOfBirth: '1914-04-01',
    gender: 'Nữ',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Ngọc Trìu',
    dateOfBirth: '1927-08-01',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Tấn Gi Trọng',
    dateOfBirth: '1913-01-01',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Trữ',
    dateOfBirth: '1926-01-09',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trương Hòa Trung',
    dateOfBirth: '1930-01-15',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Bùi Công Trừng',
    dateOfBirth: '1905-11-11',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Xuân Trường',
    dateOfBirth: '1918-03-08',
    gender: 'Nam',
    province: 'Sơn Tây',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đoàn Trọng Truyến',
    dateOfBirth: '1922-01-15',
    gender: 'Nam',
    province: 'Thừa Thiên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Tú',
    dateOfBirth: '1912-08-19',
    gender: 'Nam',
    province: 'Hưng Yên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Văn Tư',
    dateOfBirth: '1933-04-01',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Tuân',
    dateOfBirth: '1922-11-01',
    gender: 'Nam',
    province: 'Hồng Quảng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Khắc Tuân',
    dateOfBirth: '1920-08-15',
    gender: 'Nam',
    province: 'Hà Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Huy Tuấn (Hoàng Tường)',
    dateOfBirth: '1919-09-01',
    gender: 'Nam',
    province: 'Nam Định',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phan Trọng Tuệ',
    dateOfBirth: '1917-07-07',
    gender: 'Nam',
    province: 'Sơn Tây',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Tôn Thất Tùng',
    dateOfBirth: '1912-02-15',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Hữu Tước',
    dateOfBirth: '1913-10-13',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Văn Tước',
    dateOfBirth: '1930-03-01',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Tương',
    dateOfBirth: '1910-05-01',
    gender: 'Nam',
    province: 'Bình Thuận',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Công Tường',
    dateOfBirth: '1915-08-10',
    gender: 'Nam',
    province: 'Gò Công',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Công Tựu',
    dateOfBirth: '1918-08-29',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Danh Tuyên (Nguyễn Văn Luận)',
    dateOfBirth: '1911-08-20',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Văn Tỵ',
    dateOfBirth: '1916-03-14',
    gender: 'Nam',
    province: 'Phú Thọ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Vân',
    dateOfBirth: '1916-02-26',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ngô Huy Văn',
    dateOfBirth: '1902-11-25',
    gender: 'Nam',
    province: 'Bắc Giang',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Trọng Vận',
    dateOfBirth: '1937-09-02',
    gender: 'Nam',
    province: 'Sơn Tây',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Thị Thục Viên',
    dateOfBirth: '1903-01-20',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Văn Viễn (Nguyễn Đạt)',
    dateOfBirth: '1929-09-15',
    gender: 'Nam',
    province: 'Hà Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Tống Đức Viễn',
    dateOfBirth: '1904-04-18',
    gender: 'Nam',
    province: 'Tân An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Dương Văn Viện',
    dateOfBirth: '1935-11-13',
    gender: 'Nam',
    province: 'Sơn Tây',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Viện',
    dateOfBirth: '1915-05-25',
    gender: 'Nam',
    province: 'Quảng Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Hoàng Quốc Việt',
    dateOfBirth: '1905-05-28',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đặng Thái Vinh',
    dateOfBirth: '1930-08-10',
    gender: 'Nam',
    province: 'Thái Nguyên',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Quang Vinh',
    dateOfBirth: '1922-11-24',
    gender: 'Nam',
    province: 'Thái Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phùng Thị Vinh',
    dateOfBirth: '1931-05-01',
    gender: 'Nữ',
    province: 'Khu tự trị Thái Mèo',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Trọng Vĩnh',
    dateOfBirth: '1916-10-01',
    gender: 'Nam',
    province: 'Nghệ An',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Vĩnh (Nguyễn Văn Ước)',
    dateOfBirth: '1910-10-01',
    gender: 'Nam',
    province: 'Hải Dương',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Linh mục Nguyễn Thế Vịnh (Nguyễn Thế Vịnh)',
    dateOfBirth: '1904-06-06',
    gender: 'Nam',
    province: 'Ninh Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Ngọc Vỡi',
    dateOfBirth: '1919-06-01',
    gender: 'Nam',
    province: 'Ninh Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Thị Vọng',
    dateOfBirth: '1922-11-01',
    gender: 'Nữ',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Hy Vọng',
    dateOfBirth: '1920-02-20',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Phong Vũ',
    dateOfBirth: '1920-07-20',
    gender: 'Nam',
    province: 'Thanh Hoá',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Vừng',
    dateOfBirth: '1930-03-18',
    gender: 'Nam',
    province: 'Hà Tĩnh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Minh Vỹ (Tôn Thất Vỹ)',
    dateOfBirth: '1914-07-17',
    gender: 'Nam',
    province: 'Khánh Hoà',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đinh Văn Xếp',
    dateOfBirth: '1921-08-15',
    gender: 'Nam',
    province: 'Phú Thọ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nguyễn Xiển',
    dateOfBirth: '1907-07-27',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Vũ Văn Xin',
    dateOfBirth: '1923-01-01',
    gender: 'Nam',
    province: 'Hà Đông',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Đặng Thị Xuân',
    dateOfBirth: '1930-07-13',
    gender: 'Nữ',
    province: 'Sơn Tây',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Lê Thị Xuyến',
    dateOfBirth: '1909-12-09',
    gender: 'Nam',
    province: 'Quảng Nam',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Ngô Thị Xuyến',
    dateOfBirth: '1934-10-25',
    gender: 'Nữ',
    province: 'Phú Thọ',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trần Thị Xuyến',
    dateOfBirth: '1929-01-11',
    gender: 'Nữ',
    province: 'Quảng Bình',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Trương Minh Ý',
    dateOfBirth: '1931-06-21',
    gender: 'Nam',
    province: 'Bắc Ninh',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Nghiêm Xuân Yêm',
    dateOfBirth: '1913-03-19',
    gender: 'Nam',
    province: 'TP Hà Nội',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  },
  {
    no: 2,
    name: 'Phạm Thị Yến',
    dateOfBirth: '1920-01-01',
    gender: 'Nữ',
    province: 'Hồng Quảng',
    district: '',
    percentage: 0,
    cityOfBirth: '',
    degree: '',
    active: true
  }
];

export default members;
