export const cities = [
  { city: 'Cau Dien', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Cau Giay', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Chuc Son', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Dai Nghia', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Dong Anh', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Dong Da', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Ha Dong', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Hai BaTrung', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Hanoi', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Hoan Kiem', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Kim Bai', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Lien Quan', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Quoc Oai', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Soc Son', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Tay Ho', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Thach That', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Thanh Xuan', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Van Dien', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Van Dinh', state: 'Hanoi', country: 'Vietnam' },
  { city: 'Ho Chi Minh City', state: 'Ho Chi Minh City', country: 'Vietnam' }
];
