export default [
  { code: 'AED', name: 'United Arab Emirates dirham' },
  { code: 'AFN', name: 'Afghan afghani' },
  { code: 'AFN', name: 'Afghan afghani' },
  { code: 'ALL', name: 'Albanian lek' },
  { code: 'AMD', name: 'Armenian dram' },
  { code: 'AOA', name: 'Angolan kwanza' },
  { code: 'ARS', name: 'Argentine peso' },
  { code: 'AUD', name: 'Australian dollar' },
  { code: 'AZN', name: 'Azerbaijani manat' },
  { code: 'BDT', name: 'Bangladeshi taka' },
  { code: 'BIF', name: 'Burundian franc' },
  { code: 'BOB', name: 'Botswana pula' },
  { code: 'BYN', name: 'Belarusian ruble' },
  { code: 'CAD', name: 'Canadian dollar' },
  { code: 'CDF', name: 'Congolese franc' },
  { code: 'CHF', name: 'Swiss franc' },
  { code: 'CLP', name: 'Chilean peso' },
  { code: 'CNY', name: 'Chinese yuan' },
  { code: 'COP', name: 'Colombian peso' },
  { code: 'CRC', name: 'Costa Rican colón' },
  { code: 'CUP', name: 'Cuban peso' },
  { code: 'CZK', name: 'Czech koruna' },
  { code: 'DOP', name: 'Dominican peso' },
  { code: 'DZD', name: 'Algerian dinar' },
  { code: 'EGP', name: 'Egyptian pound' },
  { code: 'ETB', name: 'Ethiopian birr' },
  { code: 'EUR', name: 'Euro' },
  { code: 'GBP', name: 'British pound' },
  { code: 'GEL', name: 'Georgian lari' },
  { code: 'GHS', name: 'Ghanaian cedi' },
  { code: 'GMD', name: 'Gambian dalasi' },
  { code: 'GNF', name: 'Guinean franc' },
  { code: 'GTQ', name: 'Guatemalan quetzal' },
  { code: 'GYD', name: 'Guyanese dollar' },
  { code: 'HNL', name: 'Honduran lempira' },
  { code: 'HTG', name: 'Haitian gourde' },
  { code: 'HUF', name: 'Hungarian forint' },
  { code: 'ILS', name: 'Israeli new shekel' },
  { code: 'INR', name: 'Indian rupee' },
  { code: 'IQD', name: 'Iraqi dinar' },
  { code: 'IRR', name: 'Iranian rial' },
  { code: 'ISK', name: 'Icelandic króna' },
  { code: 'JMD', name: 'Jamaican dollar' },
  { code: 'JPY', name: 'Japanese yen' },
  { code: 'KDR', name: 'Indonesian rupiah' },
  { code: 'KES', name: 'Kenyan shilling' },
  { code: 'KGS', name: 'Kyrgyzstani som' },
  { code: 'KHR', name: 'Cambodian riel' },
  { code: 'KPW', name: 'North Korean won' },
  { code: 'KRW', name: 'South Korean won' },
  { code: 'KZT', name: 'Kazakhstani tenge' },
  { code: 'LAK', name: 'Lao kip' },
  { code: 'LKR', name: 'Sri Lankan rupee' },
  { code: 'LRD', name: 'Liberian dollar' },
  { code: 'LYD', name: 'Libyan dinar' },
  { code: 'MDL', name: 'Moldovan leu' },
  { code: 'MGA', name: 'Malagasy ariary' },
  { code: 'MKD', name: 'Macedonian denar' },
  { code: 'MMK', name: 'Burmese kyat' },
  { code: 'MNT', name: 'Mongolian tögrög' },
  { code: 'MRU', name: 'Mauritanian ouguiya' },
  { code: 'MUR', name: 'Mauritian rupee' },
  { code: 'MWK', name: 'Malawian kwacha' },
  { code: 'MXN', name: 'Mexican peso' },
  { code: 'MYR', name: 'Malaysian ringgit' },
  { code: 'MZN', name: 'Mozambican metical' },
  { code: 'NGN', name: 'Nigerian naira' },
  { code: 'NIO', name: 'Nicaraguan córdoba' },
  { code: 'NOK', name: 'Norwegian krone' },
  { code: 'NZD', name: 'New Zealand dollar' },
  { code: 'PEN', name: 'Peruvian sol' },
  { code: 'PGK', name: 'Papua New Guinean kina' },
  { code: 'PHP', name: 'Philippine peso' },
  { code: 'PKR', name: 'Pakistani rupee' },
  { code: 'PLN', name: 'Polish złoty' },
  { code: 'PRB', name: 'Transnistrian ruble' },
  { code: 'PYG', name: 'Paraguayan guaraní' },
  { code: 'RON', name: 'Romanian leu' },
  { code: 'RSD', name: 'Serbian dinar' },
  { code: 'RUB', name: 'Russian ruble' },
  { code: 'RWF', name: 'Rwandan franc' },
  { code: 'SBD', name: 'Solomon Islands dollar' },
  { code: 'SCR', name: 'Seychellois rupee' },
  { code: 'SDG', name: 'Sudanese pound' },
  { code: 'SEK', name: 'Swedish krona' },
  { code: 'SGD', name: 'Singapore dollar' },
  { code: 'SLL', name: 'Sierra Leonean leone' },
  { code: 'SLS', name: 'Somaliland shilling' },
  { code: 'SOS', name: 'Somali shilling' },
  { code: 'SRD', name: 'Surinamese dollar' },
  { code: 'SSP', name: 'South Sudanese pound' },
  { code: 'SYP', name: 'Syrian pound' },
  { code: 'THB', name: 'Thai baht' },
  { code: 'TJS', name: 'Tajikistani somoni' },
  { code: 'TMT', name: 'Turkmenistan manat' },
  { code: 'TND', name: 'Tunisian dinar' },
  { code: 'TOP', name: 'Tongan paʻanga' },
  { code: 'TRY', name: 'Turkish lira' },
  { code: 'TTD', name: 'Trinidad and Tobago dollar' },
  { code: 'TWD', name: 'New Taiwan dollar' },
  { code: 'TZS', name: 'Tanzanian shilling' },
  { code: 'UAH', name: 'Ukrainian hryvnia' },
  { code: 'UGX', name: 'Ugandan shilling' },
  { code: 'USD', name: 'United States dollar' },
  { code: 'UYU', name: 'Uruguayan peso' },
  { code: 'UZS', name: 'Uzbekistani soʻm' },
  { code: 'VES', name: 'Venezuelan bolívar soberano' },
  { code: 'VND', name: 'Vietnamese đồng' },
  { code: 'VUV', name: 'Vanuatu vatu' },
  { code: 'WST', name: 'Samoan tālā' },
  { code: 'YER', name: 'Yemeni rial' },
  { code: 'ZAR', name: 'South African rand' },
  { code: 'ZMW', name: 'Zambian kwacha' }
];
