import { tables } from '../../models/postgre';

const {
  musicArtists: { name: table, schema }
} = tables;

export { table, schema };

export const rows: Array<any> = [
  { name: '16 Typh' },
  { name: 'Ái Phương' },
  { name: 'Amee' },
  { name: 'Andree Right Hand' },
  { name: 'Anh Tú' },
  { name: 'Bằng Kiều' },
  { name: 'Bảo Anh' },
  { name: 'Bảo Thy' },
  { name: 'Bích Phương' },
  { name: 'Big Daddy' },
  { name: 'Binz' },
  { name: 'Bray' },
  { name: 'Bùi Anh Tuấn' },
  { name: 'Cá Hồi Hoang' },
  { name: 'Cam' },
  { name: 'Cao Thái Sơn' },
  { name: 'Châu Đăng Khoa' },
  { name: 'Chi Dân' },
  { name: 'Chillies' },
  { name: 'Da Lab' },
  { name: 'Đàm Vĩnh Hưng' },
  { name: 'Đạt G' },
  { name: 'Datmaniac' },
  { name: 'Dế Choắt' },
  { name: 'Đen Vâu' },
  { name: 'Đông Nhi' },
  { name: 'DrRoc' },
  { name: 'Đức Phúc' },
  { name: 'Dương Hoàng Yến' },
  { name: 'Emcee L' },
  { name: 'Emily' },
  { name: 'Erik' },
  { name: 'F' },
  { name: 'GDucky' },
  { name: 'Giang Hồng Ngọc' },
  { name: 'Gil Lê' },
  { name: 'Gin Tuấn Kiệt' },
  { name: 'Hà Anh Tuấn' },
  { name: 'Hà Lê' },
  { name: 'Hà Trần' },
  { name: 'Hải Sâm' },
  { name: 'Han Sara' },
  { name: 'Hằng Bingboong' },
  { name: 'Hành Or' },
  { name: 'Hạnh Sino' },
  { name: 'Hari Won' },
  { name: 'Hiền Hồ' },
  { name: 'Hiếu Thứ Hai' },
  { name: 'Hồ Ngọc Hà' },
  { name: 'Hồ Quang Hiếu' },
  { name: 'Hòa Minzy' },
  { name: 'Hoài Lâm' },
  { name: 'Hoàng Dũng' },
  { name: 'Hoàng Thùy Linh' },
  { name: 'Hoàng Tôn' },
  { name: 'Hoàng Yến Chibi' },
  { name: 'Hoaprox' },
  { name: 'Hương Giang Idol' },
  { name: 'Hương Ly' },
  { name: 'Hương Tràm' },
  { name: 'ICD' },
  { name: 'Isaac' },
  { name: 'Jack' },
  { name: 'Jang Mi' },
  { name: 'JayKii' },
  { name: 'JSOL' },
  { name: 'Juky San' },
  { name: 'Jun Phạm' },
  { name: 'JustaTee' },
  { name: 'Kara' },
  { name: 'Karik' },
  { name: 'Kay Trần' },
  { name: 'Khánh Phương' },
  { name: 'Khói' },
  { name: 'Khởi My' },
  { name: 'Kiên' },
  { name: 'Kimese' },
  { name: 'Lăng LD' },
  { name: 'Lê Bảo Bình' },
  { name: 'Lê Cát Trọng Lý' },
  { name: 'Lê Hiếu' },
  { name: 'Lệ Quyên' },
  { name: 'Lil Wuyn' },
  { name: 'Lip B' },
  { name: 'Liz Kim Cương' },
  { name: 'LK' },
  { name: 'Lona' },
  { name: 'Lor' },
  { name: 'Lou Hoàng' },
  { name: 'Low G' },
  { name: 'Lyly' },
  { name: 'Lynk Lee' },
  { name: 'Magazine' },
  { name: 'Mai Tiến Dũng' },
  { name: 'Masew' },
  { name: 'Maya' },
  { name: 'MC Ill' },
  { name: 'Mia' },
  { name: 'Min' },
  { name: 'Minh ' },
  { name: 'Hằng' },
  { name: 'Minh Cà Ri' },
  { name: 'Miu Lê' },
  { name: 'MONSTAR' },
  { name: 'Mr Siro' },
  { name: 'Mỹ Tâm' },
  { name: 'Negav' },
  { name: 'Ngô Hồng Quang' },
  { name: 'Ngô Kiến Huy' },
  { name: 'Ngọt' },
  { name: 'Nguyên Hà' },
  { name: 'Nguyễn Trần Trung Quân' },
  { name: 'Nguyễn Trọng Tài' },
  { name: 'Noo Phước Thịnh' },
  { name: 'Only C' },
  { name: 'Orange' },
  { name: 'OSad' },
  { name: 'Pha Lê' },
  { name: 'Phạm Quỳnh Anh' },
  { name: 'Phan Đình Tùng' },
  { name: 'Phan Mạnh Quỳnh' },
  { name: 'Phúc Du' },
  { name: 'Phùng Khánh Linh' },
  { name: 'Phương Ly' },
  { name: 'R.I.C' },
  { name: 'Rhymastic' },
  { name: 'Rich Choi' },
  { name: 'Ricky Star' },
  { name: 'RPT Gonzo' },
  { name: 'RPT MCK' },
  { name: 'RTee' },
  { name: 'SlimV' },
  { name: 'Sơn Tùng MTP' },
  { name: 'Soobin Hoàng Sơn' },
  { name: 'SpaceSpeaker' },
  { name: 'ST' },
  { name: 'Suboi' },
  { name: 'Suni Hạ Linh' },
  { name: 'Tage' },
  { name: 'Táo' },
  { name: 'Thái Đinh' },
  { name: 'Thái Tuyết Trâm' },
  { name: 'Thành Draw' },
  { name: 'Thiều Bảo Trâm' },
  { name: 'Thịnh Suy' },
  { name: 'Thu Thủy' },
  { name: 'Thùy Chi' },
  { name: 'Thủy Tiên' },
  { name: 'Tiên Cookie' },
  { name: 'Tiên Tiên' },
  { name: 'Tim' },
  { name: 'TLinh' },
  { name: 'Tóc Tiên' },
  { name: 'Touliver' },
  { name: 'Trang' },
  { name: 'Trịnh Thăng Bình' },
  { name: 'Trọng Hiếu' },
  { name: 'Tronie' },
  { name: 'Trúc Nhân' },
  { name: 'Trung Bảo' },
  { name: 'Trung Quân Idol' },
  { name: 'Uyên Linh' },
  { name: 'Văn Mai Hương' },
  { name: 'Vũ Cát Tường' },
  { name: 'Vũ.' },
  { name: 'Vương Anh Tú' },
  { name: 'Will' },
  { name: 'Wowy' },
  { name: 'Xesi' },
  { name: 'Yanbi' },
  { name: 'Yến Lê' },
  { name: 'Yến Trang' }
];
