name: GitHub Pages Deploy

on:
  push:
    paths:
      - "web/**"
      - ".github/workflows/**"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.9.0"
      - name: Yarn
        uses: borales/actions-yarn@v2.0.0
      - name: Build
        working-directory: web/react
        run: yarn install && yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.WEB_DEPLOY_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: web/react/build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
