name: Heroku Node Deploy

on:
  push:
    paths:
      - "server/node/**"
      - ".github/workflows/heroku-node.yml"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.9.0"
      - name: Set up Yarn
        uses: borales/actions-yarn@v2.0.0
      - name: Set up Compilers
        run: sudo apt-get install libpq-dev g++ make
      - name: App - Build Server
        working-directory: ./server/node
        run: yarn install && yarn build
      - name: Heroku - Login to Container registry
        working-directory: ./server/node
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Heroku - Build and push
        working-directory: ./server/node
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push web --app vietnamd
      - name: Heroku - Release
        working-directory: ./server/node
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app vietnamd
